# Generated by Django 4.2 on 2023-12-07 22:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0002_alter_customuser_options_alter_customuser_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='availability',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='department',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='customuser',
            name='dob',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='customuser',
            name='gender',
            field=models.CharField(default='Unknown', max_length=50),
        ),
        migrations.AddField(
            model_name='customuser',
            name='level',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='customuser',
            name='other_names',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='customuser',
            name='picture',
            field=models.ImageField(default='profile.jpg', upload_to='user_auth/static/'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(default='User', max_length=50),
        ),
        migrations.AddField(
            model_name='customuser',
            name='skills',
            field=models.CharField(default='No skills yet', max_length=50),
        ),
        migrations.AddField(
            model_name='customuser',
            name='surname',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='customuser',
            name='title',
            field=models.CharField(default='', max_length=50),
        ),
    ]
